insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '화장실 악취 없애기', '양치 후 주기적으로 양치물을 변기통에 뱉고 10분 후 물을 내리면 화장실에서 악취가 사라진다',sysdate,35,38,47);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '계란 터지지 않게 삶기', '계란을 삶기 전에 한 시간 정도 실온에 둔 다음 소금을 약간 넣어 주거나 식초를 몇 방울 넣으면 터지지 않고 잘 삶아진다',sysdate,13,4,4);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '눅눅해진 김 바삭하게 만들기', '눅눅해진 김을 전자레인지에 살짝만 돌려주면 다시 바삭바삭해진다',sysdate,34,6,28);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '옷에 묻은 볼펜자국 지우기', '옷에 볼펜자국이 묻었을 때는 물파스로 싹싹 문질러 주면 볼펜자국이 말끔히 사라진다',sysdate,48,19,23);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '쌀 벌레 방지하기', '쌀 안에 청양고추나 까지 않은 마늘을 넣어둠녀 쌀 벌레가 생기는 것을 방지할 수 있다',sysdate,112,13,12);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '기름때 묻은 벽지 복원', '기름때가 잘 지워지지 않는 벽지는 걸레나 수건에 맥주를 묻혀 닦아 내면 쉽게 지워진다',sysdate,34,42,12);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '냉장고 냄새 쉽게 제거하기', '냉장고에 먹다 남은 소주를 뚜껑을 연 채로 넣어 두면 냄새가 쉽게 없어진다',sysdate,439,39,26);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '좁은 공간 악취 없애기', '사과 반쪽을 좁은 공간에 하룻밤 놔두면 냄새가 말끔히 제거된다',sysdate,32,10,49);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '물병에 담긴 식물 오래 기르기', '화병에 꽂을 때 소다수를 조금 넣어주면 쉽게 시들지 않고 오래 간다',sysdate,24,9,48);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '옷에 묻은 잉크 얼룩 지우기', '옷에 묻은 잉크 얼룩은 하룻밤 동안 해당 부위를 우유에 담가두었다가 빨아주면 깨끗이 없어진다',sysdate,3,32,2);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '화장실의 물때, 얼룩 지우기', '화장실의 더러운 물때 혹은 얼룩들을 지우려면 버터와 고운 소금, 우유를 섞어 닦아주면 새것과 같이 윤이 난다',sysdate,5,4,0);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '하수구 뚫기', '하수구가 막히면 거친 소금을 한 주먹 넣고 뜨거운 물을 부어주면 잘 뚫린다',sysdate,13,13,5);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '삶는 빨래 하양게 만들기', '거름망에 마른 계란 껍질을 넣고 옷을 함께 삶아주면 눈 같이 하얗게 된다',sysdate,39,20,25);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '물건에 있는 가격표, 상표 지우기', '가격표나 상표가 붙어 있던 자리에 남아있는 흔적은 식용유로 닦으면 쉽게 제거 된다',sysdate,34,15,10);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '양파 싹 나지 않게하기', '양파를 사오면 싹이 나오는데, 이 때 양파 봉지에 빵 한 쪽을 넣어두면 쉽게 싹이 자라지 못한다',sysdate,227,327,27);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '거울이나 유리 닦을 때', '젖은 숙너에 식초를 묻혀 닦으면 깨끗하게 얼룩이 지워진다. 냄새는 자연스럽게 휘발된다',sysdate,42,20,38);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '색이 바랜 플라스틱 용기 복원', '색이 바랜 플라스틱 용기나 색바랜 창문틀, 화분 등은 남은 버터를 묻혀 닦아줌녀 다시 본래 색을 되찾는다',sysdate,0,2,2);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '저린 발 빠르게 풀기', '발이 저릴 때는 다리를 X자로 교차하고 30초 정도 꿇었다 일어나면신기하게 저림이 사라진다',sysdate,33,26,5);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '딸꾹질 멈추기', '딸꾹질은 혀를 잡아당겨 신경에 자극을 주면 멈추게 된다',sysdate,345,45,8);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '변기 물때 없애는 방법', '변기의 물때를 없앨 때는 김빠진 콜라를 하용하면 된다. 콜라에 함유된 스트르산이 깨끗하게 만들어준다',sysdate,29,4,34);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '횐색 양말 색 복원하기', '흰색 면양말을 오래 신어 본래의 색을 찾을 수 없을 때는 레몬껍질을 두어조각 넣어주면 새햐얗게 된다',sysdate,0,1,36);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '검은 옷에 묻은 먼지 제거', '검은 옷에 묻은 먼지들은 스펀지로 털어내면 손 쉽게 뗄 수 있다',sysdate,33,48,46);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '상온에 둔 병음료, 캔음료 빠르게 냉각하기', '상온에 있던 미지근한 캔음료, 병음료는 물에 적신 키친타올에 감싼 후 냉장고에 18분가량 넣어두면 시원해진다',sysdate,8,14,15);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '옷장, 수납장 밑 물건 찾을 때', '청소기에 스타킹을 감싸 고정시킨 후 청소기를 작동시키면 잃어버린 물건을 찾을 수 있다',sysdate,28,9,16);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '끓어 넘치는 냄비 물 안정시키기', '끓거나 삶는 요리를 할 때에는 냄비 위에 나무 주걱을 올려 놓으면 끓어 넘치는 것을 방지할 수 있다',sysdate,15,8,22);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '과자 눅눅하지 않게 보관하기', '먹다 남은 과자에 각설탕을 넣어 보관하면 눅눅해지는 것을 방지할 수 있다',sysdate,331,42,31);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '검게 물든 팔꿈치와 무릎 복원', '씻을 때 레몬조각을 팔꿈치와 무릎에 문질러주면 본래 색을 되찾을 수 있다',sysdate,1,438,38);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '욕실 거울에 김 서림 방지', '욕실 거울에 김이 서릴 때는 거울에 비누칠을 한 뒤 마른 수건으로 닦아내면 김이 잘 서리지 않는다',sysdate,12,41,8);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '마른 식빵 촉촉하게 만들기', '말라서 딱딱해진 식빵 사이에 새 식빵을 끼워주면 다시 촉촉해진다',sysdate,35,19,29);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '붙인 우표 안전하게 떼기', '잘못 붙인 우표를 잘 떼려면 냉각 통에 잠시 넣엇다가 뜯으면 흔적이 남지 않는다',sysdate,45,9,10);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '쓰레기통 냄새 제거하기', '쓰레기통에서 냄새가 많이 올라온다면 밑바닥에 신문지를 여러 장 겹쳐 깔아놓고 표백제를 뿌려두면 냄새가 사라진다',sysdate,124,26,24);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '보온병 깨끗하게 세척하기', '보온병에 잘게 부순 달걀껍질과 물을 넣어 흔들어주면 보온병이 깨끗하게 청소된다',sysdate,20,3,25);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '스마트폰 스피커 증폭시키기', '스마트폰으로 노래를 들을 때 사기그릇에 넣어두면 소리를 크게 들을 수 있다',sysdate,1,1,36);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '요리할 때 돼지고기 잡냄새 없애기', '돼지고기를 요리할 때 커피를 한 스푼만 넣으면 잡냄새를 말끔히 없애주는 효과가 있다',sysdate,0,24,32);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '손에 묻은 잉크 지우기', '귤껍질의 즙을 이용해 손에 묻은 잉크를 손쉽게 지울 수 있다',sysdate,44,25,44);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '꿀 깔끔하게 뜨기', '숟가락을 뜨거운 물에 한 번 담궜다가 뺀 후 꿀을 푸면 깔끔하게 뜰 수 있다',sysdate,24,8,43);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '건전지 조금 더 쓰기', '건전지 수명이 다 되었을 때 망치나 드라이버로 건전지의 옆면을 4~3번 가량 두드리면 조금 더 오래 작동한다',sysdate,3,417,17);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '고기 먹고 체했을 때 대처하기', '고기를 먹고 체했을 때는 파인애플을 먹으면 금방 속이 풀린다',sysdate,30,1,33);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '벽에 손 쉽게 못질하기', '망치로 벽에 못을 박을 때 못에 기름칠을 해주면 거짓말처럼 잘 들어간다. 기름은 휘발되면서 못이 잘 빠지거나 녹슬지 않는다',sysdate,27,16,27);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '와이셔츠 변색 막기', '땀으로 인해서 와이셔츠의 목이나 겨드랑이에 누렇게 변색되는 걸 알콜과 물을 1:1로 섞어 가볍게 두드려주면 어느 정도 예방할 수 있다',sysdate,45,0,19);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '냉동 고기 오래 보관하기', '냉동고기는 랩으로 여러 번 두껍게 싼 뒤 냉동실에 넣얻면 오랫동안 보관할 수 있다',sysdate,8,3,40);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '생강 보관하는 방법', '생강은 곰팡이가 필 수 있기 때문에 꼭 껍질을 벗긴 뒤 보관을 해야한다. 냉동 보관을 하는 것이 포인트',sysdate,216,16,46);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '젖은 신발 빨리말리기', '습한날 젖은 신말을 말릴 때 신발안에 신문지를 구겨넣으면 좋다',sysdate,21,49,34);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '흰색 속옷 빨때는 쌀뜨물', '흰색 속옷을 빨 때 쌀뜨물에 몇 번 행궈 내면 생감이 잘 살아난다',sysdate,19,28,21);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '다 쓴 향수병은 옷장에 넣기', '향수병의 뚜껑을 열고 옷장 안에 넣어 두면 옷에 향기가 스며들어 좋은 향기를 머금을 수 있게 해준다',sysdate,0,5,45);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '눌러붙은 석쇠 닦을 때', '음식 찌꺼기와 기름기가 눌러붙은 석쇠는 중성세제를 탄 물에 담가 불린다음 칫솔로 구석구석 닦아낸다',sysdate,14,14,41);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '채소의 비타민을 보호하는 방법', '채소를 데칠 때 소금을 넣어주면 비타민C가 파괴되는 것을 줄일 수 있다',sysdate,136,36,38);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '재킷 잘 다릴 수 있는 방법', '재킷을 다룰 때 수건을 얹은 의자 등받이에 걸친 다음 다림질 한다',sysdate,28,11,12);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '소세지 건강하게 먹는 방법', '햄이나 소세지는 조리전 물에 살짝 데쳐주면 짜지 않게 먹을 수 있으며 건강에 좋다',sysdate,13,40,29);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '싱크대 곰팡이 없애려면', '부엌 싱크대나 찬장 등에 곰팡이가 슬었을 때 식초를 묻힌 마른 행주로 닦으면 없앨 수 있다',sysdate,45,42,13);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '세면대 찌든 때 닦을 때', '찌든 때는 시간이 지나면 잘 닦이지 않기 때문에 목욕이나 샤워 뒤에 남은 물에 소다를 넣고 바로바로 닦는 것이 좋다',sysdate,44,42,23);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '옷의 변색 여부 아는 방법', '빨려는 옷의 변색 여부를 알려면 옷 귀퉁이를 흰천으로 싸고 따뜻한 비눗물 속에 넣고 비벼보면 알 수 있다',sysdate,425,1,25);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '마늘 변색을 막는 방법', '마늘을 빻을 때 양파를 조금 넣어두면 변색 되지 않는다',sysdate,7,14,7);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '바닥 윤나게 하기', '깨끗한 걸레를 쌀뜨물에 담갔다 꼭 짜서 바닥을 여러번 닦아주면 윤이나는 바닥이 된다',sysdate,6,49,6);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '깨진 유리조각 처리하기', '깨진 유리조각을 처리할 때는 넓은 테이프로 쓸어내면 미세한 조각까지 치울 수 있다',sysdate,33,49,33);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '전자레인지 청소할 때', '전자레인지를 청소할 때 뜨거운 물을 담은 그릇을 넣고 2~3분정도 돌려주면 수증기가 나와 때를 닦기가 편해진다',sysdate,441,41,46);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '방문 손잡이 때 지우는 방법', '방문 손잡이는 무즙을 천에 묻혀서 닦으면 말끔하게 지워진다. 특히 잘 지워지지 않을 때 효과 만점이다',sysdate,38,35,27);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '손에 양파냄새 뺄 때', '요리하다 밴 양파와 파냄새는 식초를 넣은 따뜻한 물에 씻으면 냄새가 사라진다',sysdate,8,42,35);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '가죽 제품에 얼룩이지면', '기름 얼룩이 졌을 때 마른 걸레를 닦고 샴푸하면 잘 제거될 수 있기 때문에 알아두면 좋다',sysdate,420,20,20);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '그릇의 찌든 때', '헝겊에 소금과 식초를 묻혀 사기그릇을 닦으면 찌든 때가 잘 제거된다',sysdate,29,45,8);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '실내 담배연기 줄이기', '밀폐된 실내에서 연기가 차는 것을 줄이려면 모래를 담은 유리컵에 초를 꽂은 뒤 불을 켜두면 잘 빨아들인다',sysdate,40,40,35);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '옷에 묻은 김칫국 지우기', '김치국은 옷의 안과 밖에 양파즙을 바르고 하루쯤 지나고 나서 세탁하면 쉽게 지울 수 있다',sysdate,48,48,37);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '기름기는 사과껍질', '스테인리스 재질에 기름 때가 묻으면 사과껍질을 비비면 좋다',sysdate,28,9,2);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '김밥 자를 때', '김밥을 자를 때 식초에 칼을 담갔다 자르면 매우 잘 잘라진다. 이쑤시개를 칼의 한 쪽 면에 붙여도 좋다',sysdate,49,41,10);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '행주를 삶을 때', '행주를 삶을 때 레몬 껍질을 넣어주면 된다',sysdate,38,33,5);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '운동화 세탁할 때', '변색된 흰 운동화는 낡은 칫솔에 치약을 묻혀 문지르고 물로 빨면 효과가 매우 좋다',sysdate,32,31,15);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '간장, 설탕을 넣은 조림요리를 할 때', '간장과 설탕을 함께 넣는 조림요리는 설탕을 먼저 녹인 뒤 간장을 넣어야 맛깔스럽다',sysdate,9,16,46);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '먹다 남아 김 빠진 맥주', '김빠진 맥주는 바닥이 넓은 컵에 소주를 넣은 뒤 맥주를 넣어 마신다',sysdate,38,33,38);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '벨트를 오래 사용하려면', '벨트의 구멍 안쪽에 투명 매니큐어를 발라두면, 오래 사용이 가능하고 고장날 확률이 적다',sysdate,2,132,32);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '칼이 잘 들지 않을 때', '칼이 안들 때 알루미늄 포일에 문지르면 제법 쓸만해진다. 가위도 마찬가지다.',sysdate,145,18,45);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '검은 옷의 먼지를 털 때', '검은 옷의 먼지를 털 때는 옷솔보다는 스펀지로 하거나 고무장갑으로 하는 것이 매우 효과적이다',sysdate,44,41,36);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '국수를 삶을 때', '국수를 삶을 때 끓는 물에 참기름을 한 숟가락 넣어주면 면발이 서로 달라붙지 않고 맛도 부드러워진다',sysdate,29,18,48);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '방습제를 옷장에 두면', '김에 들어 있는 실리카겔을 모아 옷장에 넣어두면 효과적이다',sysdate,33,13,24);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '변색된 '||CHR(39)||'은'||CHR(39)||'신구', '누렇게 변할 때 레몬즙으로 닦고 뜨거운 물로 헹구면 자국이 잘 그리고 말끔하게 지워진다',sysdate,0,4,39);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '와인잔 씻을 때', '물과 베이킹파우더를 섞어 만든 얇은 반죽으로 와인잔을 문질러 물로 씻어내면 윤을 내는데 효과가 있다',sysdate,19,22,40);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '정전기가 잘 일어나는 옷', '정전기가 잘 일어나는 소재의 옷은 욕실에 걸어둔 뒤 적당히 습기가 스며들게 하고 입으면 잘 일어나지 않는다',sysdate,8,0,26);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '테이프 끝에 단추를 붙이면', '급히 써야할 대 테이프 시작 부분을 찾기 쉬워져 매우 좋다. 동일하게 클립을 붙여놓아도 좋다',sysdate,31,18,16);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '스위치 주변 손때', '손때는 지우개로 문질러 지워내면 손쉽게 지워진다',sysdate,25,0,20);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '밥상의 눌은 자국 지우기', '밥상의 눌은 자국은 마른 수건에 마요네즈를 묻혀 닦아주면 눌은 자국이 없어지면서 밥상이 코팅 된다',sysdate,419,19,39);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '쓰레받기 정전기를 막으려면', '양초를 쓰레받기 앞뒤로 잘 문질러 두면 머리카락, 먼지가 달라 붙지 않는다',sysdate,8,24,36);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '나무 주방용품 세철 후 ', '대나무 김발이나 나무주걱을 씻은 후 전자레인지에 건조시키면 얼룩이 생기지 않는다',sysdate,41,39,28);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '시든 채소 싱싱하게 만들기', '각설탕과 식초를 한 두 방울 떨어뜨린 물에 담구면 채소가 싱싱하게 변한다',sysdate,19,448,48);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '식용유를 엎질렀을 때', '밀가루를 뿌려주면 기름을 흡수해서 완벽하게 제거할 수 있다',sysdate,8,12,26);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '달걀을 깨지지 않게 삶으려면', '삶을 때 달걀의 위 혹은 아래 끝에 작은 구멍을 뚫어두면 된다. 바늘정도의 구멍이면 충분하다',sysdate,411,39,11);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '니코틴 자국이 남았을 때', '금연 후 손가락에 니코틴 자국이 남았을 때 레몬즙 + 과산화수소 수용액 '||CHR(39)||'옥시풀'||CHR(39)||'이 가장 효과가 좋다',sysdate,9,48,48);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '머리카락에 껌이 붙었을 때', '헤어크림을 잔뜩 바르고 나서 마른 수건으로 떼어내면 껌을 손쉽게 떼어낼 수 있다',sysdate,34,11,2);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '키보드 손때', '피아노나 컴퓨터 키보드의손때는 부드러운 천에 치약을 발라 닦아내면 깨끗해진다',sysdate,49,25,15);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '콩자반을 만들 때', '콩자반을 만들 콩과 물을 1:3으로 보온병에 넣어두면 시간을 절약',sysdate,34,16,20);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '카펫을 청소하는 방법', '카펫을 청소할 때 먼저 카펫에 소금을 뿌리면, 소금이 먼지들을 흡수해 한결 청소가 잘 된다',sysdate,1,15,48);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '옷을 삶지 않고 삶은 효과보기', '세탁할 옷에 가루비누를 칠하고 비닐봉지에 넣고 볕에 30분 정도 놓아두고 빨면 삶은 효과를 볼 수 있다',sysdate,149,36,49);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '줄어든 스웨터 복구', '세탁을 잘못해 줄어든 스웨터나 카디건은 암모니아를 조금 넣은 물에 담갔다가 잡아당겨 늘려주면 된다',sysdate,3,42,20);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '야채를 신선하게 보관하는 방법', '야채를 물에 적셔 신문지로 말아 냉장고에 보관하면 2배 이상 신선하다. 잉크가 걱정되면 종이 타올로 한다',sysdate,1,3,10);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '만두피 안 풀어지게 하려면', '만두피를 반죽할 때 계란과 참기름을 섞으면 잘 안풀린다',sysdate,5,3,42);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '김이 서리는 유리창에', '습기를 닦아낸 유리창에 샴푸를 묻혀 다시 닦아주면 김이 잘 서리지 않는다',sysdate,29,6,3);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '식은 튀김요리 데울 때', '식은 튀김요리를 다시 데울 때 기름을 두른 팬에 술을 한 두방울 넣어주면 느끼한 기름냄새가 줄어든다',sysdate,18,21,8);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '매니큐어, 잉크병 안 열릴 때', '두 병 이외에도 뚜껑과 병 사이 진득한 것이 꼈을 때 드라이기로 뚜껑 부분을 30초간 가열하면 쉽게 열린다',sysdate,3,35,29);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '도마에 냄새 막으려면', '고기나 생선을 썰 때 도마 위에 종이 한 장을 깔면 도마에 냄새가 스며들거나 더러워지지 않는다',sysdate,38,8,41);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '음식에 식초가 많이 들어갔을 때', '식초가 너무 많이 들어간 음식에 술을 뿌리면 신맛이 덜해진다',sysdate,8,14,28);
insert into livingPoint values(livingpoint_seq.nextval, 1, 'jeongyi', '감자 껍질 쉽게 벗기기', '감자를 끓는 물에 살짝 데쳐 겉을 수세미로 문지르면 껍질을 손 쉽게 벗길 수 있다',sysdate,321,21,26);
